from gym.envs.registration import register

register(
    id='hide-and-seek-v0',
    entry_point='mae_envs.envs:HideAndSeek',
    kwargs={
          'n_substeps': 15,
          'horizon': 80,
          'deterministic_mode': False,
          'floor_size': 6.0,
          'grid_size': 30,
          'door_size': 2,
          'n_hiders': 1,
          'n_seekers': 1,
          'max_n_agents': None,
          'n_boxes': 2,
          'n_ramps': 1,
          'n_elongated_boxes': 0,
          'rand_num_elongated_boxes': False,
          'n_min_boxes': None,
          'box_size': 0.5,
          'boxid_obs': False,
          'box_only_z_rot': True,
          'rew_type': 'joint_zero_sum',
          'lock_box': True,
          'grab_box': True,
          'lock_ramp': True,
          'lock_type': 'any_lock_specific',
          'lock_grab_radius': 0.25,
          'lock_out_of_vision': True,
          'grab_exclusive': False,
          'grab_out_of_vision': False,
          'grab_selective': False,
          'box_floor_friction': 0.2,
          'other_friction': 0.01,
          'gravity': [0,0,-50],
          'action_lims': (-0.9,0.9),
          'polar_obs': True,
          'scenario': 'quadrant',
          'quadrant_game_hider_uniform_placement': False,
          'p_door_dropout': 0.0,
          'n_rooms': 4,
          'random_room_number': True,
          'prob_outside_walls': 1.0,
          'n_lidar_per_agent': 0,
          'visualize_lidar': False,
          'compress_lidar_scale': None,
          'hiders_together_radius': None,
          'seekers_together_radius': None,
          'prep_fraction': 0.4,
          'prep_obs': False,
          'team_size_obs': False,
          'restrict_rect': None,
          'penalize_objects_out': False,
          'n_food': 0,
          'food_radius': None,
          'food_respawn_time': None,
          'max_food_health': 1,
          'food_together_radius': None,
          'food_rew_type': 'selfish',
          'eat_when_caught': False,
          'food_reward_scale': 1.0,
          'food_normal_centered': False,
          'food_box_centered': False,
          'n_food_cluster': 1
    },
)

register(
    id='box-locking-v0',
    entry_point='mae_envs.envs:BoxLocking',
    kwargs={
          'n_substeps': 15,
          'horizon': 80,
          'deterministic_mode': False,
          'floor_size': 6.0,
          'grid_size': 30,
          'door_size': 2,
          'n_agents': 1,
          'fixed_agent_spawn': False,
          'lock_box': True,
          'grab_box': True,
          'grab_selective': False,
          'lock_type': 'any_lock_specific',
          'lock_grab_radius': 0.25,
          'grab_exclusive': False,
          'grab_out_of_vision': False,
          'lock_out_of_vision': True,
          'box_floor_friction': 0.2,
          'other_friction': 0.01,
          'gravity': [0,0,-50],
          'action_lims': (-0.9,0.9),
          'polar_obs': True,
          'scenario': 'quadrant',
          'p_door_dropout': 0.0,
          'n_rooms': 4,
          'random_room_number': True,
          'n_lidar_per_agent': 0,
          'visualize_lidar': False,
          'compress_lidar_scale': None,
          'n_boxes': 2,
          'box_size': 0.5,
          'box_only_z_rot': False,
          'boxid_obs': True,
          'boxsize_obs': True,
          'pad_ramp_size': True,
          'additional_obs': {},
          # lock-box task
          'task_type': 'all',
          'lock_reward': 5.0,
          'unlock_penalty': 7.0,
          'shaped_reward_scale': 0.25,
          'return_threshold': 0.1,
          # ramps
          'n_ramps': 0
    },
)

register(
    id='blueprint-construction-v0',
    entry_point='mae_envs.envs:BlueprintConstruction',
    kwargs={
          'n_substeps': 15,
          'horizon': 80,
          'deterministic_mode': False,
          'floor_size': 6.0,
          'grid_size': 30,
          'n_agents': 1,
          'n_rooms': 4,
          'random_room_number': True,
          'scenario': 'empty',
          'door_size': 2,
          'n_sites': 3,
          'n_elongated_sites': 0,
          'site_placement': 'uniform_away_from_walls',
          'reward_infos': [{'type': 'construction_dense'}],
          'n_boxes': 2,
          'n_elongated_boxes': 0,
          'n_min_boxes': None,
          'box_size': 0.5,
          'box_only_z_rot': False,
          'lock_box': True,
          'grab_box': True,
          'grab_selective': False,
          'lock_grab_radius': 0.25,
          'lock_type': 'any_lock_specific',
          'grab_exclusive': False,
          'grab_out_of_vision': False,
          'lock_out_of_vision': True,
          'box_floor_friction': 0.2,
          'other_friction': 0.01,
          'gravity': [0,0,-50],
          'action_lims': (-0.9,0.9),
          'polar_obs': True,
          'n_lidar_per_agent': 0,
          'visualize_lidar': False,
          'compress_lidar_scale': None,
          'boxid_obs': True,
          'boxsize_obs': True,
          'team_size_obs': False,
          'additional_obs': {}
    },
)

register(
    id='shelter-construction-v0',
    entry_point='mae_envs.envs:ShelterConstruction',
    kwargs={
        'n_substeps': 15,
        'horizon': 80,
        'deterministic_mode': False,
        'floor_size': 6.0,
        'grid_size': 30,
        'n_agents': 1,
        'objective_diameter': [1, 1],
        'objective_placement': 'center',
        'num_rays_per_side': 25,
        'shelter_reward_scale': 1,
        'n_boxes': 2,
        'n_elongated_boxes': 0,
        'box_size': 0.5,
        'box_only_z_rot': False,
        'lock_box': True,
        'grab_box': True,
        'grab_selective': False,
        'lock_grab_radius': 0.25,
        'lock_type': 'any_lock_specific',
        'grab_exclusive': False,
        'grab_out_of_vision': False,
        'lock_out_of_vision': True,
        'box_floor_friction': 0.2,
        'other_friction': 0.01,
        'gravity': [0, 0, -50],
        'action_lims': (-0.9, 0.9),
        'polar_obs': True,
        'n_lidar_per_agent': 0,
        'visualize_lidar': False,
        'compress_lidar_scale': None,
        'boxid_obs': True,
        'boxsize_obs': True,
        'team_size_obs': False,
        'additional_obs': {}
    },
)
